Framerate converter
Seize/joy4 pull request #4
Opened 2018-10-17 10:31 UTC by a-rose

# PR Type

- [x] Feature
- [ ] Bug fix
- [ ] Docs

## Description

Add framerate conversion capabilities using libavfilter.
The framerate is automatically converted if the encoder's fps setting doesn't match exactly the input framerate

## Notes for your reviewer

2018-10-17 10:55 UTC, JulienBreux requested changes

2018-10-17 10:55 UTC, JulienBreux commented on cgo/ffmpeg/video.go
> +type FramerateConverter struct {
Best practices to comment your code.
(even if the lib have no comments)

2018-10-17 10:55 UTC, JulienBreux commented on cgo/ffmpeg/video.go
> +
Best practices to comment your code.
(even if the lib have no comments)
...

2018-10-17 13:58 UTC, JulienBreux commented
@a-rose up for comments

2018-10-17 14:00 UTC, a-rose commented
> @a-rose up for comments

I'm almost done cleaning up :)

2018-10-17 14:22 UTC, JulienBreux requested changes
Sorry but I am not made to understand ☺️

2018-10-17 14:22 UTC, JulienBreux commented on cgo/ffmpeg/video.go
> +type VideoFramerate struct {
Comments here

2018-10-17 14:22 UTC, JulienBreux commented on cgo/ffmpeg/video.go
> +func (v VideoFrame) GetFramerate() (num, den int) {
Comments here

2018-10-17 14:22 UTC, JulienBreux commented on cgo/ffmpeg/video.go
> +func (v *VideoFrame) SetFramerate(num, den int) {
Comments here

2018-10-17 14:46 UTC, JulienBreux approved these changes

2018-10-17 14:47 UTC, merged

2021-01-04 12:52 UTC, cedricve commented
@a-rose  great. I'm just wondering how to properly calculate the FrameRate if this is note set.

https://github.com/Seize/joy4/blob/master/codec/h264parser/parser.go#L650

2021-01-06 15:29 UTC, a-rose commented
> @a-rose great. I'm just wondering how to properly calculate the FrameRate if this is note set.
> 
> https://github.com/Seize/joy4/blob/master/codec/h264parser/parser.go#L650

If the timing information is not present, you're probably dealing with variable FPS, as is often the case with mobile video streaming.